### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by mfketggo** [tsenger/SigAnima#1]
compile the project on eclipse,the plugins is JCOP3.2.8.it can choose JCOP v2.4.1 R2,but compile is err log follow:
Description Resource    Path    Location    Type
SignatureX cannot be resolved   SigAnimaApplet.java /SigAnima-master/src/de/tsenger/siganima/applet line 131    Java Problem
The import com.nxp cannot be resolved   SigAnimaApplet.java /SigAnima-master/src/de/tsenger/siganima/applet line 43 Java Problem
SignatureX cannot be resolved   SigAnimaApplet.java /SigAnima-master/src/de/tsenger/siganima/applet line 131    Java Problem

I would like to test you project,if you can help me dispose the issue

**Comment by tsenger** [comment]
Hi there, you will need JCOP v2.4.2 R3 card with the corresponding NXP JCOP libraries. These include the needed SignatureX.ALG_ECDSA_PLAIN algorithm. This plain signature algorithm isn't very common on other JAVA cards, so I don't know if there are other cards with the same functionality.
