### ISSUE TITLE
Is this lib maintained? Any update for more recent cards? 

### ISSUE THREAD

**Issue by Eithcowich** [tsenger/SigAnima#2]

**Comment by tsenger** [comment]
Currently there a no plans for an updated version. The applet should worked also an recent cards as long as they provide a function similar to the JCOP specific algorithm SignatureX.ALG_ECDSA_PLAIN. 
In JavaCard 3.0.5 this algorithm is called Signature.SIG_CIPHER_ECDSA_PLAIN. So if you are using a card supporting this, the applet should work there.
