### ISSUE TITLE
Build Project to .cap

### ISSUE THREAD

**Issue by mumbleStar** [tsenger/SigAnima#3]
Hi Tsenger,

very nice code + docs. Thank u for providing this.

My questions is how to build this project to a .cap file so I can install it onto the javacard.

Thanks alote

best regards
mumbleStar

**Comment by tsenger** [comment]
Hello mumbleStar,
you are right it would be nice to have a build chain. Shouldn't be to complex. I will add it if I have some time. Meanwhile you can have a look at my other Javacard-Projekt [CCU2](https://github.com/tsenger/CCU2F/tree/master/CCU2F). There you found a build.xml, tools to build in the tools folder and the Javacard libs in the extlibs folder. 
best regards

**Comment by mumbleStar** [comment]
Hello tsenger,

perfect, thank you for the support

best regards

**Comment by Aiosa** [comment]
The easiest way is to use Applet Playground by Martin Paljak
