### ISSUE TITLE
Host application

### ISSUE THREAD

**Issue by Aiosa** [tsenger/SigAnima#4]
Hello,

nice project - and also documentation (which is so rare!). I am missing only one thing - does this applet meet any API supported by some hosts - and thus sending raw APDU is not required, such as OpenSC, OpenPGP, Cryptonit and some others..? I couldn't find any.

Thank you.

**Comment by tsenger** [comment]
Hi,
unfortunately the applet uses a proprietary API that is not supported by other tools yet.

Am 13. Februar 2020 16:07:42 WEZ schrieb Aiosa <notifications@github.com>:
>Hello,
>
>nice project - and also documentation (which is so rare!). I am missing
>only one thing - does this applet meet any API supported by some hosts
>- and thus sending raw APDU is not required, such as OpenSC, OpenPGP,
>Cryptonit and some others..? I couldn't find any.
>
>Thank you.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tsenger/SigAnima/issues/4

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
